<?php

/**
 * Settings
 * TO DO: settings in back end
 */

/**
 * Implements hook_block_info().
 */
function custom_blog_archive_block_info(){
  $blocks = array();
  //$blocks['custom_blog_archive'] = array(
  //  'info' => t('Blog archive'),
  //  'cache' => DRUPAL_NO_CACHE,
  //);

  $blocks['accordion_blog_archive'] = array(
    'info' => t('Accordion Blog archive'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['categories_blog'] = array(
    'info' => t('Categorie del blog'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  $blocks['tags_blog'] = array(
    'info' => t('Tag del blog'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function custom_blog_archive_block_view($delta = ''){
  $block = array();
  
  switch ($delta) {
    //case 'custom_blog_archive':
    //
    //  $block['subject'] = t('Blog archive');
    //  $block['content']['archivio'] = array(
    //    '#markup' => custom_blog_archive_view(),
    //  );
    //
    //  $css_path = drupal_get_path('module', 'custom_blog_archive').'/style.css';
    //  $js_path = drupal_get_path('module', 'custom_blog_archive').'/jquery.script.js';
    //  $block['content']['#attached']['css'][] = $css_path;
    //  $block['content']['#attached']['js'][] = $js_path;
    //
    //break;

    case 'accordion_blog_archive':
      $block['subject'] = t('Accordion Blog Archive');
      $block['content'] = accordion_blog_archive_view();
    break;

    case 'categories_blog':
      $block['subject'] = t('Categories Archive');
      $block['content'] = categories_blog_view();
    break;

    case 'tags_blog':
      $block['subject'] = t('Tags Archive');
      $block['content'] = tags_blog_view();
    break;

  }
  
  return $block;
}

/**
 * Categorie Blog Archive
 */
function categories_blog_view(){
  $query = db_select('taxonomy_term_data', 't');
  $query->fields('t', array('tid','name'));
  $query->condition('t.vid', 1, '=');
  $query->join('taxonomy_index', 'ti', 't.tid = ti.tid');
  $result = $query->execute();

  foreach ($result as $item) {
    $tid = $item->tid;
    $categories[$tid]['name'] = $item->name;
    if (isset($categories[$tid]['number'])){
      $categories[$tid]['number'] = $categories[$tid]['number'] + 1;
    } else {
      $categories[$tid]['number'] = 1;
    }
  }
  
  foreach ($categories as $tid => $category) {
    $text = $category['name'] . ' (' . $category['number'] . ')'; 
    $data[$tid] = array(
      '#markup' => '<p class="small spazio-5">' . l($text, 'taxonomy/term/' . $tid) . '</p>',
    );
  }

  return $data;
}

/**
 * Tags Blog Archive
 */
function tags_blog_view(){
  $query = db_select('taxonomy_term_data', 't');
  $query->fields('t', array('tid','name'));
  $query->condition('t.vid', 2, '=');
  $query->join('taxonomy_index', 'ti', 't.tid = ti.tid');
  $result = $query->execute();

  $tags = false;
  foreach ($result as $item) {
    $tid = $item->tid;
    $tags[$tid]['name'] = $item->name;
    if (isset($tags[$tid]['number'])){
      $tags[$tid]['number'] = $tags[$tid]['number'] + 1;
    } else {
      $tags[$tid]['number'] = 1;
    }
  }

  $opt['attributes']['class'] = array('btn','btn-default', 'btn-flat');

  $data['tag'] = array(
    '#prefix' => '<div class="archive-tags"><ul class="archive-tags-ul">',
    '#suffix' => '</ul></div>',
  );
  
  if ($tags){
    foreach ($tags as $tid => $tag) {
      $text = $tag['name'];
      $data['tag'][$tid] = array(
        '#markup' => '<li>' . l($text, 'taxonomy/term/' . $tid, $opt) . '</li>',
      );
    } 
  }

  //$data['#prefix'] = '<div class="well">';
  //$data['#suffix'] = '</div>';

  return $data;
}

/**
 * Accordion Blog Archive view
 */
function accordion_blog_archive_view(){
  $nodes = get_all_post('news');

  $possible_years = array();
  $possible_months = array();
  $archive = array();
  
  foreach ($nodes as $node) {
    $title   = $node->title;
    $date = strtotime($node->field_date['und'][0]['value']);
    $path    = url('node/' . $node->nid);
    $year    = date("Y", $date);
    $month   = date("F", $date);
    
    if (in_array($year, $possible_years) == FALSE) {
      $possible_years[] = $year;
    }
    
    if (in_array($month, $possible_months) == FALSE) {
      $possible_months[] = $month;
    }
    
    $archive[$year][$month][] = array(
      'title' => $title,
      'path' => $path,
      'nid' => $node->nid,
    );
  }

  // ANNI
  foreach ($archive as $k_year => $mesi) {
    $Ypanels[$k_year] = array(
      '#theme' => 'smiletrap_panel',
      '#id' => 'p-' . $k_year,
      '#title' => $k_year,
      '#content' => array(
        '#theme' => 'smiletrap_accordion',
        '#id' => 'ay-' . $k_year,
      ),
    );

    // MESI
    $Mpanels = array();
    foreach ($mesi as $k_month => $posts) {

      $ym = $k_year . '-' . $k_month;
      $count = count($posts);
      $titolo_mese = '<h4 class="panel-title">' . $k_month . ' (' . $count  . ')</h4>';

      $Mpanels[$k_month] = array(
        '#theme' => 'smiletrap_panel',
        '#id' => 'am-' . $ym,
        '#title' => $titolo_mese,
      );

      // POST
      if (is_array($posts) == TRUE) {
        foreach ($posts as $k_post => $post) {
          if (is_array($post) == TRUE) {
            $Mpanels[$k_month]['#content'][$k_post] = array(
              '#markup' => '<p class="small">' . l($post['title'], 'node/' . $post['nid']) . '</p>',
            );
          }
        }
      }
    }
    $Ypanels[$k_year]['#content']['#elements'] = $Mpanels;
    $Ypanels[$k_year]['#content']['#prefix'] = '<div class="sub-archive">';
    $Ypanels[$k_year]['#content']['#suffix'] = '</div>';
  }
  
  $data['accordion'] = array(
    '#theme' => 'smiletrap_accordion',
    '#id' => 'blog-archive-accordion',
    '#elements' => $Ypanels,
    '#options' => array(
      'fade' => TRUE,
    ),
  );

  return $data;
}

/**
 * Get all post from the blog
 */
function get_all_post($type){
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->propertyCondition('status', 1)
    ->propertyCondition('type', array($type))
    ->fieldOrderBy('field_date', 'value', 'DESC')
    ->range(0, 9999);
  $result = $query->execute();
  $nodes = node_load_multiple(array_keys($result['node']));
  return $nodes;
}

/**
 * Custom function constructs block
 */
function custom_blog_archive_view(){
  $type = "news";
  
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->propertyCondition('status', 1)
    ->propertyCondition('type', array($type))
    ->fieldOrderBy('field_date', 'value', 'DESC')
    ->range(0, 9999);
  $result = $query->execute();
  $nodes = node_load_multiple(array_keys($result['node']));
  
  $possible_years = array();
  $possible_months = array();
  $archive = array();
  
  foreach ($nodes as $node) {
    $title   = $node->title;
    $date = strtotime($node->field_date['und'][0]['value']);
    $path    = url('node/' . $node->nid);
    $year    = date("Y", $date);
    $month   = date("F", $date);
    
    if (in_array($year, $possible_years) == FALSE) {
      $possible_years[] = $year;
    }
    
    if (in_array($month, $possible_months) == FALSE) {
      $possible_months[] = $month;
    }
    
    $archive[$year][$month][] = array(
      'title' => $title,
      'path' => $path
    );
  }
  
  $html = '<ul class="years">';
  foreach ($archive as $key => $value) {
    if (in_array($key, $possible_years) == TRUE) {
      $html .= '<li class="year"><span class="clicker">' . $key . '</span>';
      $html .= '<ul class="months">';
    }
    if (is_array($value) == TRUE) {
      $n = count($value);
      foreach ($value as $key => $value) {
        if (in_array($key, $possible_months) == TRUE) {
          $html .= '<li class="month"><span class="clicker">' . $key . ' (' . $n . ')</span>';
          $html .= '<ul class="items">';
        }
        if (is_array($value) == TRUE) {
          foreach ($value as $key => $value) {
            if (is_array($value) == TRUE) {
              $html .= '<li class="item">';
              $html .= '<a href="' . $value['path'] . '">' . $value['title'] . '</a>';
              $html .= '</li>';
            }
          }
        }
        $html .= '</ul></li>';
      }
    }
    $html .= '</ul></li>';
  }
  
  return $html;
}

/**
 * preprocess node blog page
 */
function custom_blog_archive_preprocess_node(&$vars){
  if ($vars['nid'] == 5){
    if ($vars['view_mode'] == 'teaser' || $vars['view_mode'] == 'full'){
      // Visualizzo tutti i post con pager
      $nodes = _get_all_post_paged('news', 8);

      if ($vars['view_mode'] == 'teaser'){
        $nodes = _get_all_post_paged('news', 4);  
      }

      $vars['content']['posts']['#prefix'] = '<div class="row row-blog-archive">';
      $vars['content']['posts']['#suffix'] = '</div>';
      foreach ($nodes as $key => $node) {
        $vars['content']['posts'][$key] = node_view($node, 'child');
      }
      $vars['content']['pager'] = array(
        '#prefix' => '<hr>',
        'data' => array(
          '#theme' => 'pager',
          '#tags' => array(),
        ),
        '#weight' => 10,
      );

      if ($vars['view_mode'] == 'teaser'){
        $vars['content']['pager']['#printed'] = TRUE;
        $vars['content']['posts']['#weight'] = 10;
      }
    }
  }
}

/**
 * Get all post from the blog
 */
function _get_all_post_paged($type, $n){
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->propertyCondition('status', 1)
    ->propertyCondition('type', array($type))
    ->fieldOrderBy('field_date', 'value', 'DESC')
    ->pager($n);
  $result = $query->execute();
  $nodes = node_load_multiple(array_keys($result['node']));
  return $nodes;
}
